# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/BTDialogInputPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordInputDialog(object):
    def setupUi(self, PasswordInputDialog):
        PasswordInputDialog.setObjectName("PasswordInputDialog")
        PasswordInputDialog.resize(342, 94)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PasswordInputDialog.sizePolicy().hasHeightForWidth())
        PasswordInputDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editPassword = QtWidgets.QLineEdit(PasswordInputDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editPassword.sizePolicy().hasHeightForWidth())
        self.editPassword.setSizePolicy(sizePolicy)
        self.editPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPassword.setClearButtonEnabled(False)
        self.editPassword.setObjectName("editPassword")
        self.gridLayout_2.addWidget(self.editPassword, 3, 0, 1, 1)
        self.buttonShowHidePassword = QtWidgets.QToolButton(PasswordInputDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/pwd_show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonShowHidePassword.setIcon(icon)
        self.buttonShowHidePassword.setObjectName("buttonShowHidePassword")
        self.gridLayout_2.addWidget(self.buttonShowHidePassword, 3, 1, 1, 1)
        self.labelMessage = QtWidgets.QLabel(PasswordInputDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMessage.sizePolicy().hasHeightForWidth())
        self.labelMessage.setSizePolicy(sizePolicy)
        self.labelMessage.setObjectName("labelMessage")
        self.gridLayout_2.addWidget(self.labelMessage, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(PasswordInputDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PasswordInputDialog)
        self.buttonBox.accepted.connect(PasswordInputDialog.accept)
        self.buttonBox.rejected.connect(PasswordInputDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PasswordInputDialog)

    def retranslateUi(self, PasswordInputDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordInputDialog.setWindowTitle(_translate("PasswordInputDialog", "Dialog"))
        self.buttonShowHidePassword.setText(_translate("PasswordInputDialog", "..."))
        self.labelMessage.setText(_translate("PasswordInputDialog", "Password:"))
